### PR TITLE
Support for CHAP frames

### PR DESCRIPTION
**Pull request by markusahlstrand**
Thanks for a great library!

We needed to support id3v2 chapter frames (http://id3.org/id3v2-chapters-1.0) and added this to the library.

### CODE REVIEW

**Comment by biril** [comment]
Thanks a lot for the PR :+1: 

I will be taking a look at the link that you provided - I was actually unaware of the addendum - as I'm keen to write a test before merging. Which I'm otherwise very much looking forward to.

Would you be happy to squash those two commits into one and `push -f`ing the PR so that we avoid those webstorm files going into the project's history?

**Comment by markusahlstrand** [comment]
I'll give the squashing a go and see if I can add some tests to it. Thanks

**Comment by markusahlstrand** [comment]
Guess you would need to include a reference file for the tests? I haven't found any good really samples yet.

**Comment by biril** [comment]
Here's some info in case you want to look into adding tests (I should really include these in the `README`):

The test suite is written on Jasmine and you should be able to run it with `npm test` (after having `npm install`ed). It's comprised of 3 spec files and a couple of test mp3s which you will find under `test/`.

`test/spec/mp3-parser.spec.js` contains trivial specs not worth talking about. 

`test/spec/read-id3v2.3-iso-8859-1.spec.js` loads up the test mp3 `test/id3v2.3-iso-8859.mp3` and executes `readId3v2Tag` on it. It then runs specs that assert that all expected frames have been discovered and are observed to be of the expected values.

`test/spec/read-id3v2.3-ucs-2.spec.js` works the same way, with `test/id3v2.3-ucs-2.mp3` as input. However it only deals with (runs expectations for) the subset of ID3v2 frames that may be encoded in UCS-2.

Generally speaking, adding tests for a frame `XXXX` involves
* Editing the `-iso-8859-1.mp3` file to add an `XXXX` frame (or multiple if allowed), that contains some specific value(s) (that can be encoded in ISO-8859-1).
* Adding a spec to the `-iso-8859-1.spec.js` file to assert that the `XXXX` frame is read and contains the specific value(s).
* If `XXXX` supports UCS-2 content then repeat this for the `-ucs-2.mp3` / `-ucs-2.spec.js` pair, this time implementing expectations for UCS-2 encoded values.

To add frames to the test mp3s I use [Kid3 ID3 Tagger](http://kid3.sourceforge.net/).

**Comment by markusahlstrand** [comment]
Thanks for the info! I'll see if I can update the test-files and add some tests tomorrow.

**Comment by markusahlstrand** [comment]
Started looking at the test but have some issues with the Kid3 ID3 Tagger. When I add the chapter frame and save the file it removes a bunch of other frames, for instance the TRDA-frame. Have you encountered this issue before?

**Comment by biril** [comment]
Hey, yes, I'm seeing similar behaviour 😕 .

I had to install the latest KID3 as my current version was oblivious to CHAP frames. And it looks like 
the current version is not liking some frames that the previous one let me edit. On first glance it's not clear which, as it's just marking them as 'Unknown' - and deleting (some of) them when saved with a new CHAP frame.

Thanks a lot for letting me know, it looks like this warrants a bit of proper looking into, which I hope to be able to do in the next couple of days. Obviously feel free to kick the tires further. In any case I'll be keeping you posted.

Cheers.

**Comment by markusahlstrand** [comment]
Would it be ok to add a separate test file with the chapter frames? Tried a few different tools to add the CHAP-frames to the existing files, but so far no luck.

**Comment by biril** [comment]
Okay, looks like this version of KID3 (possibly among other things)

* does not handle **TRDA** (which you mentioned) as well as **TSIZ**
* won't tolerate **TORY** frames with values of more than 4 chars (which is actually not unreasonable as these are meant to represent dates)
* won't tolerate an odd number of entries in **IPLS**, such as `one|two|three`

When the test mp3s are saved frames get truncated and/or removed (regardless of the **CHAP** frame) which causes the tests to fail. _Additionally_ it looks like there may be a defect in how **IPLS** is parsed (`id3v2.readFrameContentIpls`) which throws `RangeError: Invalid typed array length`. This didn't occur with mp3s edited by previous versions of KID3 (or other random mp3s I've tested). I'll have to investigate this further..

All in all there seems to be number of blockers for this. You could indeed bypass them by doing a separate test-mp3 _and test-suite_ pair. And we could look into merging _that_, initially. _If_ you want to expedite the pull request that is. It's probable that down the road it'll all be merged back into the two original test suites. But feel free :+1:.

----

P.S. Is anything worth mentioning, among the other tools you tried for editing ID3? I've been meaning to look into alternative/additional utilities, besides KID3, for maintaining the test suite (that run on a Mac, ideally).

----

P.P.S. I took another look at your commit and the indentation is a bit off. There's also a duplicate declaration for `offsetTrm`. Please make sure `npm run lint` doesn't give any errors / warnings on your branch. Thanks!

**Comment by markusahlstrand** [comment]
Yes, found a few issues with my initial PR ;) Also found the bug in the IPLS frame and fixed that in another branch. If we can start with a separate test-file for CHAP-frames I can clean up the PR with the changes.
So far I tried the podcasts chapters tool (from the appstore) which crashed when trying to add a chapter to the testfiles and the BBC chapter tool (http://www.bbc.co.uk/opensource/projects/ID3v2_Chapter_Tool) which I honestly couldn't get working at all.
I'll take a look at a few more tools for adding the CHAP frames before I give up.

**Comment by biril** [comment]
Yes, we can go with a separate mp3 test file. Just make sure to create a matching separate test suite for it as well. I wouldn't want to have one of the two original specs loading more that one file. 

Perhaps it would even make sense to keep the test suite for the CHAP frame separate given that it supports an arbitrary number of embedded sub-frames. Perhaps it's generally a good call.

So no luck with other tools huh. Still, given you'll be working on an separate mp3 I suppose you'll be able to use KID3 to edit solely CHAP frames.

**Comment by markusahlstrand** [comment]
Tried mp3tag and tagScanner (both for windows) now as well. Can't find any chapter support there. I'll go ahead and create a separate test file for chapters.

**Comment by markusahlstrand** [comment]
Added a separate test file for the chap frames and a couple of tests. Wasn't quite sure if we should add all possible frames as nested frames to the chap-frame or if it's enough with a couple?
Fixed some logic issues in the parsing code for CHAP frames and a minor fix for the ILPS frame. Also changed my indentation to match the project and resolved the jshint errors.

Would be great with some feedback on the tests to know if it's on the right track. I can squash the commits once we think the code is in a good state.

**Comment by markusahlstrand** [comment]
Thanks for the review, all good and valid points. Hopefully I'll be able to push a fix for them in the next couple of days.

**Comment by markusahlstrand** [comment]
Sorry for taking so long to get around to push the last changes. Also managed to mess up a bit when squashing the commits. Hope it will work out now.

**Comment by biril** [comment]
Thanks @markusahlstrand :+1:

**Pull request merged**
